version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./db/procedures.sql:/docker-entrypoint-initdb.d/procedures.sql

  api:
    build:
      context: ./api
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/northwind

  web:
    build:
      context: ./web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - '80:80'