version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - '5432'