version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - '5432'

  api:
    build:
      context: ./api
    ports:
      - '8000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/northwind

  web:
    build:
      context: ./web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - '80:80'